### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Holy6Papa** [gushmazuko/metasploit_in_termux#216]
**Important**
Do not duplicate, search your issue before creating one!

**Describe the bug**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. OnePlus 8]
 - OS: [e.g. Android 10]
Successfully installed mini_portile2-2.8.1
Building native extensions. This could take a while...
ERROR:  Error installing actionpack:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/3.2.0 extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.1
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.10.3.
Configuration options: --host\=aarch64-unknown-linux-android --enable-static --disable-shared --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ports/aarch64-linux-android/libxml2/2.10.3/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --disable-shared --enable-static CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0005-avoid-isnan-isinf.patch
  - 0009-allow-wildcard-namespaces.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

[{:url=>
   "https://mirror.csclub.uwaterloo.ca/gnome/sources/libxml2/2.10/libxml2-2.10.3.tar.xz",
  :sha256=>"5d2cc3d78bec3dbe212a9d7fa629ada25a7da928af432c93060ff5c17ee28a9c"}]
Extracting libxml2-2.10.3.tar.xz into tmp/aarch64-unknown-linux-android/ports/libxml2/2.10.3... ERROR, review '/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10/ext/nokogiri/tmp/aarch64-unknown-linux-android/ports/libxml2/2.10.3/extract.log' to see what happened. Last lines are:
========================================================================
tar: libxml2-2.10.3/test/relaxng/ambig_name-class.xml: Cannot hard link to ‘libxml2-2.10.3/test/relaxng/ambig_name-class2.rng’: Permission denied
tar: libxml2-2.10.3/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.10.3/test/relaxng/tutorA.rng’: Permission denied
tar: Exiting with failure status due to previous errors
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --prevent-strip
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-static
        --enable-cross-build
        --disable-cross-build
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-xml2-source-dir
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:460:in `block in execute': Failed to complete extract task (RuntimeError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:426:in `chdir'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:426:in `execute'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:413:in `extract_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:90:in `block in extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:88:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:88:in `extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.1/lib/mini_portile2/mini_portile.rb:183:in `cook'
        from extconf.rb:529:in `block (2 levels) in process_recipe'
        from extconf.rb:309:in `chdir'
        from extconf.rb:309:in `chdir_for_build'
        from extconf.rb:529:in `block in process_recipe'
        from <internal:kernel>:90:in `tap'
        from extconf.rb:428:in `process_recipe'
        from extconf.rb:782:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.13.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.13.10 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/aarch64-linux-android/3.2.0/nokogiri-1.13.10/gem_make.out
Could not locate Gemfile
Could not locate Gemfile
Could not locate Gemfile
open("/data/data/com.termux/files/usr/lib/ruby/gems/*/gems/pg-*/lib/pg_ext.so"): No such file or directory

====================== * =======================
 Suppressing Warnings
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/ruby_thread_local_var.rb: No such file or directory
sed: can't read /data/data/com.termux/files/usr/lib/ruby/gems/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb: No such file or directory
Please help me

**Comment by Holy6Papa** [comment]
How ?
