### ISSUE TITLE
[BUG] Arrange bug

### ISSUE THREAD

**Issue by Darkrevengehack** [gushmazuko/metasploit_in_termux#264]
======= * Erasing old metasploit folder... =======
================ * Downloading... ================
Cloning into '/data/data/com.termux/files/usr/opt/metasploit-framework'...
remote: Enumerating objects: 15146, done.
remote: Counting objects: 100% (15146/15146), done.
remote: Compressing objects: 100% (12994/12994), done.
Receiving objects:   0% (151/15146), 636.00 KiB | Receiving objects:   0% (151/15146), 1012.00 KiB |Receiving objects:   0% (151/15146), 1.08 MiB | 35Receiving objects:   1% (152/15146), 1.19 MiB | 32Receiving objects:   1% (152/15146), 1.26 MiB | 30Receiving objects:   1% (156/15146), 1.31 MiB | 27Receiving objects:   1% (191/15146), 1.42 MiB | 18Receiving objects:   1% (213/15146), 1.46 MiB | 14Receiving objects:   1% (252/15146), 1.56 MiB | 10Receiving objects:   1% (256/15146), 1.59 MiB | 89Receiving objects:   1% (266/15146), 1.65 MiB | 67Receiving objects:   1% (269/15146), 1.66 MiB | 61Receiving objects:   1% (271/15146), 1.71 MiB | 46Receiving objects:   1% (271/15146), 1.75 MiB | 43Receiving objects:   1% (271/15146), 1.81 MiB | 40Receiving objects:   1% (271/15146), 1.84 MiB | 39Receiving objects:   1% (275/15146), 1.85 MiB | 34Receiving objects:   1% (275/15146), 1.88 MiB | 35Receiving objects:   1% (275/15146), 1.89 MiB | 31Receiving objects:   1% (275/15146), 1.92 MiB | 26Receiving objects:   1% (275/15146), 1.94 MiB | 24Receiving objects:   1% (278/15146), 2.03 MiB | 31Receiving objects:   1% (278/15146), 2.10 MiB | 42Receiving objects:   1% (278/15146), 2.11 MiB | 35Receiving objects:   1% (278/15146), 2.17 MiB | 44Receiving objects:   1% (278/15146), 2.18 MiB | 45Receiving objects:   1% (281/15146), 2.21 MiB | 48Receiving objects:   2% (303/15146), 2.25 MiB | 50Receiving objects:   2% (372/15146), 2.29 MiB | 44Receiving objects:   2% (376/15146), 2.33 MiB | 44Receiving objects:   2% (381/15146), 2.37 MiB | 43Receiving objects:   2% (383/15146), 2.39 MiB | 51Receiving objects:   2% (393/15146), 2.45 MiB | 42Receiving objects:   2% (396/15146), 2.50 MiB | 38Receiving objects:   2% (396/15146), 2.53 MiB | 40Receiving objects:   2% (396/15146), 2.58 MiB | 38Receiving objects:   2% (396/15146), 2.61 MiB | 42Receiving objects:   2% (396/15146), 2.68 MiB | 41Receiving objects:   2% (396/15146), 2.70 MiB | 44Receiving objects:   2% (396/15146), 2.72 MiB | 39Receiving objects:   2% (396/15146), 2.74 MiB | 34Receiving objects:   2% (396/15146), 2.75 MiB | 30Receiving objects:   2% (396/15146), 2.77 MiB | 27Receiving objects:   2% (396/15146), 2.79 MiB | 24Receiving objects:   2% (396/15146), 2.82 MiB | 25Receiving objects:   2% (398/15146), 2.86 MiB | 21Receiving objects:   2% (400/15146), 2.88 MiB | 24Receiving objects:   2% (403/15146), 2.89 MiB | 24Receiving objects:   2% (408/15146), 2.93 MiB | 26Receiving objects:   2% (410/15146), 2.96 MiB | 30Receiving objects:   2% (411/15146), 2.99 MiB | 30Receiving objects:   2% (421/15146), 3.04 MiB | 32Receiving objects:   2% (428/15146), 3.05 MiB | 29Receiving objects:   2% (432/15146), 3.08 MiB | 29Receiving objects:   2% (435/15146), 3.14 MiB | 35Receiving objects:   2% (435/15146), 3.18 MiB | 35Receiving objects:   2% (435/15146), 3.21 MiB | 35Receiving objects:   2% (435/15146), 3.23 MiB | 33Receiving objects:   2% (435/15146), 3.25 MiB | 30Receiving objects:   2% (435/15146), 3.29 MiB | 33Receiving objects:   2% (435/15146), 3.29 MiB | 30Receiving objects:   2% (435/15146), 3.32 MiB | 24Receiving objects:   2% (435/15146), 3.36 MiB | 24Receiving objects:   2% (435/15146), 3.36 MiB | 21Receiving objects:   2% (435/15146), 3.38 MiB | 22Receiving objects:   2% (435/15146), 3.39 MiB | 21Receiving objects:   2% (435/15146), 3.42 MiB | 20Receiving objects:   2% (437/15146), 3.44 MiB | 22Receiving objects:   2% (445/15146), 3.46 MiB | 21Receiving objects:   2% (445/15146), 3.49 MiB | 21Receiving objects:   2% (452/15146), 3.51 MiB | 24Receiving objects:   2% (453/15146), 3.55 MiB | 25Receiving objects:   2% (454/15146), 3.58 MiB | 29Receiving objects:   3% (455/15146), 3.58 MiB | 29Receiving objects:   3% (484/15146), 3.68 MiB | 38Receiving objects:   3% (504/15146), 3.71 MiB | 42Receiving objects:   3% (530/15146), 3.73 MiB | 43Receiving objects:   3% (540/15146), 3.79 MiB | 48Receiving objects:   3% (554/15146), 3.81 MiB | 47Receiving objects:   3% (576/15146), 3.89 MiB | 47Receiving objects:   3% (591/15146), 4.21 MiB | 97Receiving objects:   3% (596/15146), 4.46 MiB | 14Receiving objects:   4% (606/15146), 5.12 MiB | 27Receiving objects:   4% (615/15146), 5.57 MiB | 36Receiving objects:   4% (619/15146), 6.04 MiB | 48Receiving objects:   4% (640/15146), 7.17 MiB | 72Receiving objects:   4% (727/15146), 8.51 MiB | 95Receiving objects:   5% (758/15146), 8.51 MiB | 95Receiving objects:   6% (909/15146), 9.25 MiB | 1.Receiving objects:   7% (1061/15146), 9.25 MiB | 1Receiving objects:   8% (1212/15146), 9.25 MiB | 1Receiving objects:   8% (1295/15146), 10.08 MiB | Receiving objects:   9% (1364/15146), 11.04 MiB | error: 1620 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
=============== * Installation... ================
./metasploit.sh: line 62: cd: /data/data/com.termux/files/usr/opt/metasploit-framework: No such file or directory
Fetching bundler-2.5.4.gem
Successfully installed bundler-2.5.4
Parsing documentation for bundler-2.5.4
Installing ri documentation for bundler-2.5.4
Done installing documentation for bundler after 1 seconds
1 gem installed

A new release of RubyGems is available: 3.4.10 → 3.5.4!
Run `gem update --system 3.5.4` to update your installation.

cat: Gemfile.lock: No such file or directory
ERROR:  While executing gem ... (Gem::OptionParser::MissingArgument)
    missing argument: -v
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/command.rb:448:in `handle_options'
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/command.rb:313:in `invoke_with_build_args'
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
        /data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
        /data/data/com.termux/files/usr/bin/gem:10:in `<main>'
Could not locate Gemfile
Fetching concurrent-ruby-1.2.2.gem
Fetching rails-html-sanitizer-1.6.0.gem
Fetching mini_portile2-2.8.5.gem
Fetching racc-1.7.3.gem
Fetching nokogiri-1.16.0.gem
Fetching minitest-5.20.0.gem
Fetching loofah-2.22.0.gem
Fetching crass-1.0.6.gem
Fetching tzinfo-2.0.6.gem
Fetching i18n-1.14.1.gem
Fetching connection_pool-2.4.1.gem
Fetching activesupport-7.1.2.gem
Fetching actionpack-7.1.2.gem
Fetching rack-3.0.8.gem
Fetching rack-test-2.1.0.gem
Fetching rails-dom-testing-2.2.0.gem
Fetching rack-session-2.0.0.gem
Fetching erubi-1.12.0.gem
Fetching builder-3.2.4.gem
Fetching actionview-7.1.2.gem
Building native extensions. This could take a while...
Successfully installed racc-1.7.3
Successfully installed mini_portile2-2.8.5
Building native extensions. This could take a while...
ERROR:  Error installing actionpack:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.16.0/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby extconf.rb
checking for whether -std=c99 is accepted as CFLAGS... yes
checking for whether -Wno-declaration-after-statement is accepted as CFLAGS... yes
checking for whether -O2 is accepted as CFLAGS... yes
checking for whether -g is accepted as CFLAGS... yes
checking for whether -Winline is accepted as CFLAGS... yes
checking for whether -Wmissing-noreturn is accepted as CFLAGS... yes
checking for whether -Wconversion -Wno-sign-conversion is accepted as CFLAGS... yes
Building nokogiri using packaged libraries.
Static linking is enabled.
Cross build is disabled.
Using mini_portile version 2.8.5
checking for iconv... yes
---------- IMPORTANT NOTICE ----------
Building Nokogiri with a packaged version of libxml2-2.12.3.
Configuration options: --host\=arm-unknown-linux-androideabi --enable-static --disable-shared --libdir\=/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.16.0/ports/arm-linux-androideabi/libxml2/2.12.3/lib --with-iconv\=yes --disable-dependency-tracking --without-python --without-readline --with-c14n --with-debug --with-threads --without-tls --disable-shared --enable-static CPPFLAGS\= CFLAGS\=-O2\ -U_FORTIFY_SOURCE\ -g\ -fPIC
The following patches are being applied:
  - 0001-Remove-script-macro-support.patch
  - 0002-Update-entities-to-remove-handling-of-ssi.patch
  - 0003-libxml2.la-is-in-top_builddir.patch
  - 0009-allow-wildcard-namespaces.patch
  - 0010-update-config.guess-and-config.sub-for-libxml2.patch
  - 0011-rip-out-libxml2-s-libc_single_threaded-support.patch

The Nokogiri maintainers intend to provide timely security updates, but if
this is a concern for you and want to use your OS/distro system library
instead, then abort this installation process and install nokogiri as
instructed at:

  https://nokogiri.org/tutorials/installing_nokogiri.html#installing-using-standard-system-libraries

Note, however, that nokogiri cannot guarantee compatibility with every
version of libxml2 that may be provided by OS/package vendors.

Extracting libxml2-2.12.3.tar.xz into tmp/arm-unknown-linux-androideabi/ports/libxml2/2.12.3... ERROR. Please review logs to see what happened:
----- contents of '/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.16.0/ext/nokogiri/tmp/arm-unknown-linux-androideabi/ports/libxml2/2.12.3/extract.log' -----
tar: libxml2-2.12.3/test/relaxng/ambig_name-class.xml: Cannot hard link to ‘libxml2-2.12.3/test/relaxng/ambig_name-class2.rng’: Permission denied
tar: libxml2-2.12.3/test/relaxng/ambig_name-class.rng: Cannot hard link to ‘libxml2-2.12.3/test/relaxng/tutorA.rng’: Permission denied
tar: Exiting with failure status due to previous errors
----- end of file -----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --prevent-strip
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-system-libraries
        --disable-system-libraries
        --use-system-libraries
        --enable-static
        --enable-cross-build
        --disable-cross-build
        --enable-cross-build
        --disable-cross-build
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-xml2-source-dir
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:612:in `block in execute': Failed to complete extract task (RuntimeError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:578:in `chdir'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:578:in `execute'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:564:in `extract_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:138:in `block in extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:136:in `each'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:136:in `extract'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/mini_portile2-2.8.5/lib/mini_portile2/mini_portile.rb:231:in `cook'
        from extconf.rb:540:in `block (2 levels) in process_recipe'
        from extconf.rb:319:in `chdir'
        from extconf.rb:319:in `chdir_for_build'
        from extconf.rb:540:in `block in process_recipe'
        from <internal:kernel>:90:in `tap'
        from extconf.rb:438:in `process_recipe'
        from extconf.rb:871:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/arm-linux-androideabi/3.2.0/nokogiri-1.16.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/nokogiri-1.16.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/extensions/arm-linux-androideabi/3.2.0/nokogiri-1.16.0/gem_make.out
Could not locate Gemfile
Could not locate Gemfile
Could not locate Gemfile
open("/data/data/com.termux/files/usr/lib/ruby/gems/*/gems/pg-*/lib/pg_ext.so"): No such file or directory

**Comment by dedshit** [comment]
@Darkrevengehack metasploit download stopped due to your network problem
also you didnt use updated one

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackLa descarga de Metasploit se detuvo debido a un problema de red y tampoco usaste una actualizada.

The metasploit I am using is yours, champion, how do I do it?

**Comment by dedshit** [comment]
your translation is broken @Darkrevengehack

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack metasploit download stopped due to your network problem also you didnt use updated one

Updating of what?

**Comment by dedshit** [comment]
dont you see EOF ?
`fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF`

**Comment by dedshit** [comment]
just uninstall the previous one & install it properly

**Comment by Darkrevengehack** [comment]
> simplemente desinstale el anterior e instálelo correctamente

Hey friend look, I need you to understand, I have termux from 0 completely installed from 0 in something new to be from 0, then I have to install metasploit, I installed it a thousand times and I still appears that I have no additional metasploit apart from that, since I started in a clean termux, but it does not let me, and when you answer this message I ask you to do me the great favor of what command to delete a metasploit, no matter why, it matters that I need a command that definitely delete metasploit and everything that occupies space on the phone.

By the way, the wifi network is perfect for this kind of errors to happen.

**Comment by dedshit** [comment]
run `termux-info`

**Comment by Darkrevengehack** [comment]
> ejecuta `termux-info`y envía esa captura de pantalla

![Screenshot_20240124-042852_Termux](https://github.com/gushmazuko/metasploit_in_termux/assets/103399387/75a365eb-3df8-431d-ad90-fd0573224415)

**Comment by dedshit** [comment]
```
rm -rf $PREFIX/lib/ruby

apt install -y binutils python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby

if [ -d "${PREFIX}/opt/metasploit-framework" ]; then
  rm -rf ${PREFIX}/opt/metasploit-framework
fi

git clone https://github.com/rapid7/metasploit-framework.git --depth=1 ${PREFIX}/opt/metasploit-framework

cd ${PREFIX}/opt/metasploit-framework

gem install bundler

NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")

gem install nokogiri -v $NOKOGIRI_VERSION -- --with-cflags="-Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-incompatible-function-pointer-types" --use-system-libraries

bundle install

gem install actionpack

bundle update activesupport

bundle update --bundler

bundle install -j$(nproc --all)

```


@Darkrevengehack  run it step by step . if any problem , mention in which step you got problem if not good to go

**Comment by Darkrevengehack** [comment]
> ```
> apt remove ruby
> 
> rm -rf $PREFIX/lib/ruby
> 
> apt install -y binutils python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git ruby
> 
> if [ -d "${PREFIX}/opt/metasploit-framework" ]; then
>   rm -rf ${PREFIX}/opt/metasploit-framework
> fi
> 
> git clone https://github.com/rapid7/metasploit-framework.git --depth=1 ${PREFIX}/opt/metasploit-framework
> 
> cd ${PREFIX}/opt/metasploit-framework
> 
> gem install bundler
> 
> NOKOGIRI_VERSION=$(cat Gemfile.lock | grep -i nokogiri | sed 's/nokogiri [\(\)]/(/g' | cut -d ' ' -f 5 | grep -oP "(.).[[:digit:]][\w+]?[.].")
> 
> gem install nokogiri -v $NOKOGIRI_VERSION -- --with-cflags="-Wno-implicit-function-declaration -Wno-deprecated-declarations -Wno-incompatible-function-pointer-types" --use-system-libraries
> 
> bundle install
> 
> gem install actionpack
> 
> bundle update activesupport
> 
> bundle update --bundler
> 
> bundle install -j$(nproc --all)
> ```
> 
> @Darkrevengehack ejecutarlo paso a paso. Si hay algún problema, mencione en qué paso tuvo el problema. Si no está listo, continúe.

Hello friend, I need you to know that as soon as I get a cell phone with more GB of internal storage, I will try what you told me, since the one I have now, only has 32 GB and what occupies more GB is the operating system.
