### ISSUE TITLE
[BUG] msfconsole tried to open /etc/resolv.conf

### ISSUE THREAD

**Issue by Def-Try** [gushmazuko/metasploit_in_termux#268]
**Important**
Do not duplicate, search your issue before creating one!
^^^ There is one issue same as this, but it's marked as completed without solution

**Describe the bug**
After installation, msfconsole just doesn't start.
**Screenshots**
```
Metasploit tip: Use the resource command to run commands from a file
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `foreach': No such file or directory @ rb_sysopen - /etc/resolv.conf (Errno::ENOENT)
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1087:in `parse_config_file'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/resolver.rb:67:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/ui/console/driver.rb:83:in `initialize'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /data/data/com.termux/files/usr/bin/msfconsole:23:in `<main>'
```

**Smartphone (please complete the following information):**
 - Device: Realme C25Y
 - OS: Android 11

**Comment by dedshit** [comment]
duplicate https://github.com/gushmazuko/metasploit_in_termux/issues/260#issuecomment-1888617189

**Comment by Def-Try** [comment]
Solution (if anyone has this problem too):
```
cd $PREFIX/opt/metasploit-framework

sed -i '0,/\"\/etc\/resolv.conf\"/s//\"\/data\/data\/com.termux\/files\/usr\/etc\/resolv.conf\"/' $(find . -name 'resolver.rb')
```
thanks to dedshit for answering that
