### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by u0a27** [gushmazuko/metasploit_in_termux#63]
I am using android 6.0.1 and when i tried to run msfconsole it showed:
Traceback (most recent call last):                      61: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `<main>'                          60: from /data/data/com.termux/files/usr/bin/msfconsole:18:in `require'                         59: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'                                           58: from /data/data/com.termux/files/home/metasploit-framework/lib/msfenv.rb:17:in `require'
        57: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `<top (required)>'                                    56: from /data/data/com.termux/files/home/metasploit-framework/config/environment.rb:2:in `require'
        55: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `<top (required)>'
        54: from /data/data/com.termux/files/home/metasploit-framework/config/application.rb:1:in `require'
        53: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails.rb:17:in `<top (required)>'
        52: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        51: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        50: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        49: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        48: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/railtie.rb:4:in `<top (required)>'
        47: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        46: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        45: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        44: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        43: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/i18n_railtie.rb:8:in `<top (required)>'
        42: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/i18n_railtie.rb:9:in `<module:I18n>'
        41: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/i18n_railtie.rb:10:in `<class:Railtie>'
        40: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:146:in `config'
        39: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:241:in `config'
        38: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        37: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        36: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        35: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        34: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/railtie/configuration.rb:3:in `<top (required)>'
        33: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        32: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        31: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        30: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/railties-6.1.4.1/lib/rails/configuration.rb:4:in `<top (required)>'
        28: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        27: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        26: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        25: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object.rb:10:in `<top (required)>'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        22: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        21: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        20: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        19: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/conversions.rb:5:in `<top (required)>'
        18: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
        13: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        11: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        10: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/xml_mini.rb:6:in `<top (required)>'
         8: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
         7: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
         6: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
         5: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
         4: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
         1: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so" load segment[8]: p_offset (0x2000) + p_filesz (0x2ec) ( = 0x22ec) past end of file (0x22ec) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)

 - Device: [samsung galaxy j2 prime]
 - OS: [android 6.0.1]
 - please help.
 - sorry for bad english and i am a noob

**Comment by gushmazuko** [comment]
Follow the steps here: https://github.com/gushmazuko/metasploit_in_termux/issues/62#issuecomment-903749537
